config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "groups#index"
  resources :users, only: :index

  resources :groups, only: [:new, :edit, :create, :update] do
    resources :messages, only: [:index, :create]
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :members
  has_many :users, through: :members
  has_many :messages

  validates :name, presence: true, uniqueness: true



  def show_last_message
    if (last_message = messages.last).present?
      last_message.text? ? last_message.text : '画像が投稿されています'
    else
      'まだメッセージはありません。'
    end
  end

end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
  mount_uploader :image, ImageUploader
  validates :text, presence: true, unless: :image?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :members
  has_many :groups, through: :members

  has_many :messages

end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    group = Group.find(params[:group_id])
    @messages = group.messages.where("id > ?", params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:update, :edit]

  def index
    groups = []
    nomessage_groups = []
    Message.order("created_at DESC").includes(:group).each do |message|
      if current_user.groups.include?(message.group)
        groups << message.group
      end
    end
    @groups = (groups + current_user.groups.order("created_at DESC")).uniq

    respond_to do |format|
      format.html
      format.json
    end
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render action: :new
    end
  end

  def edit
    @users = @group.users - [current_user]
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループを編集しました'
    else
      @users = @group.users - [current_user]
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, { user_ids: [] })
  end

  def set_group
    @group = Group.find(params[:id])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group
  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)

    groups = []
    nomessage_groups = []
    Message.order("created_at DESC").includes(:group).each do |message|
      if current_user.groups.include?(message.group)
        groups << message.group
      end
    end
    @groups = (groups + current_user.groups.order("created_at DESC")).uniq

    respond_to do |format|
      format.html
      format.json
    end
  end

  def create
    @message = Message.new(message_params)
    respond_to do |format|
      format.html {
        if @message.save
          redirect_to group_messages_path(@group), notice: 'メッセージが送信されました'
        else
          redirect_to group_messages_path(@group), alert: "メッセージを入力してください"
        end
      }
      format.json {@message.save}
    end
  end

  private
  def message_params
    params.require(:message).permit(:text, :image).merge(user_id: current_user.id, group_id: params[:group_id])
  end
  def set_group
    @group = Group.find(params[:group_id])

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    added_users = User.where(id: params[:addedIDs])
    @users = User.where("name LIKE ?","#{params[:input]}%") - added_users
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_group.html.haml
.Sidebar__groups__group{data: {id: group.id}}
  = link_to group_messages_path(group.id), class: "Sidebar__groups__group__link" do
    %h2 
      =group.name
    %p= group.show_last_message

app/views/groups/_sidebar.html.haml
.Sidebar
  .Sidebar__top
    .Sidebar__top__user
      %span #{current_user.name}
      =link_to edit_user_registration_path do
        =fa_icon 'cog'
      =link_to new_group_path do
        =fa_icon 'pencil-square-o'
  .Sidebar__groups
    = render @groups

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = form_for @group do |f|
    - if @group.errors.any?
      .chat-group-form__errors
        %h2= "#{@group.errors.full_messages.count}件のエラーが発生しました。"
        %ul
          - @group.errors.full_messages.each do |message|
            %li= message

    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :グループ名, class: 'chat-group-form__label'
      .chat-group-form__field--right
        = f.text_field :name, class: "chat_group_name chat-group-form__input", placeholder: "グループ名を入力してください"
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{for: "chat_group_チャットメンバーを追加"} チャットメンバーを追加
      .chat-group-form__field--right
        .chat-group-form__search.clearfix
          %input#user-search-field.chat-group-form__input{placeholder: "追加したいユーザー名を入力してください", type: "text"}
        #user-search-result

    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
      .chat-group-form__field--right
        .chat-group-users.js-add-user
          .chat-group-user.clearfix.js-chat-member{id: current_user.id}
            = f.hidden_field :user_ids, name: "group[user_ids][]", value: current_user.id
            %p.chat-group-user__name=current_user.name
          = render @users, f: f

    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        = f.submit class: 'chat-group-form__action-btn'

app/views/groups/index.html.haml
= render "sidebar"

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = form_for @group do |f|
    - if @group.errors.any?
      .chat-group-form__errors
        %h2= "#{@group.errors.full_messages.count}件のエラーが発生しました。"
        %ul
          - @group.errors.full_messages.each do |message|
            %li= message
    .chat-group-form__field
      .chat-group-form__field--left
        = f.label :name, class: 'chat-group-form__label'
      .chat-group-form__field--right
        = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{for: "chat_group_チャットメンバーを追加"} チャットメンバーを追加
      .chat-group-form__field--right
        .chat-group-form__search.clearfix
          %input#user-search-field.chat-group-form__input{placeholder: "追加したいユーザー名を入力してください", type: "text"}
        #user-search-result

    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{for: "chat_group_チャットメンバー"} チャットメンバー
      .chat-group-form__field--right
        .chat-group-users.js-add-user
          .chat-group-user.clearfix.js-chat-member{id: current_user.id}
            %input#group_user_ids{name: "group[user_ids][]", type: "hidden", value: current_user.id}
            %p.chat-group-user__name=current_user.name
          
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        = f.submit class: 'chat-group-form__action-btn'

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv":"Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    = yield

app/views/messages/_message.html.haml
.Contents__messages__box{data: {id: message.id}}
  %h2
    = message.user.name
    %span
      = message.created_at.strftime("%Y/%m/%d(%a) %H:%M:%S")
  %p 
    = message.text
  = image_tag message.image.to_s

app/views/messages/_sidebar.html.haml
.Sidebar
  .Sidebar__top
    .Sidebar__top__user
      %span #{current_user.name}
      =link_to edit_user_registration_path do
        =fa_icon 'cog'
      =link_to new_group_path do
        =fa_icon 'pencil-square-o'
  .Sidebar__groups
    - @groups.each do |group|
      .Sidebar__groups__group
        = link_to group_messages_path(group), class: "Sidebar__groups__group__link" do
          %h2 
            =group.name
          %p= group.show_last_message

app/views/messages/index.html.haml
= render "groups/sidebar"
.Contents
  .Contents__top
    .Contents__top__groupname
      %h2= @group.name
      %p
        Member :
        - @group.users.each do |user|
          %span
            =user.name
      = link_to "Edit", edit_group_path(params[:group_id])
  .Contents__messages
    = render @messages

  .Contents__sendmessage
    = form_for [@group, @message] do |f|
      = f.text_field :text, class: "Contents__sendmessage--textbox", placeholder: "type a message"
      = f.submit "Send", class: "Contents__sendmessage--sendbtn"
      %label.label.Contents__sendmessage--image
        = fa_icon 'picture-o',  class: 'icon'
        = f.file_field :image, class: "Contents__sendmessage--image__upload-icon"

app/views/users/_user.html.haml
.chat-group-user.clearfix.js-chat-member{id: user.id}
  = f.hidden_field :user_ids, name: "group[user_ids][]", value: user.id
  %p.chat-group-user__name=user.name
  %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn 削除